<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<Platforms>AnyCPU;x64</Platforms>
	<EnableWindowsTargeting>true</EnableWindowsTargeting>
	<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<ApplicationManifest>app.manifest</ApplicationManifest>
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	<ApplicationIcon>Resources\logo.ico</ApplicationIcon>

    <!-- Публикация под конкретную платформу -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <!-- Включаем в сборку .NET Runtime -->
    <SelfContained>true</SelfContained>
	  
	<Version>1.2.5</Version>
	<FileVersion>1.2.5</FileVersion>
	<AssemblyVersion>1.2.5</AssemblyVersion>
	<InformationalVersion>1.2.5</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Installers.7z" />
    <None Remove="Resources\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="IWshRuntimeLibrary">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>f935dc20-1cf0-11d0-adb9-00c04fd58a0b</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Installers.7z">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\logo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
	<!-- Этот блок говорит: “все файлы icons\*.ico копировать в выходную папку рядом с exe” -->
	<Content Include="Icons\*.ico">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="SharpCompress" Version="0.39.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

	<ItemGroup>
		<!-- Основные ресурсы (ResX) -->
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Docs\" />
  </ItemGroup>

</Project>